import { Geist, Geist_Mono } from "next/font/google";
import pokemon from "pokemontcgsdk";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pokehub",
  description: "Generated by create next app",
};

pokemon.configure({ apiKey: "fb989f11-3b6f-441b-9f0f-a284bd591e58" });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
